name: Push-to-EC2
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  node:
    runs-on: [ self-hosted, master ]
    steps:
    - name: Checkout the code
      uses: actions/checkout@v1
    - name: Deploy to my EC2 instance
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        REMOTE_HOST: "44.193.30.237"
        REMOTE_USER: "ubuntu"
        TARGET: "/home/ubuntu/"
    - run: pwd
    - run: sudo cp /home/ubuntu/Dockerfile ./
    - run: ls
    - name: Run build
      run: |
        sudo docker stop express-master || true
        sudo docker rm express-master  || true
        sudo docker rmi express-master  || true
        sudo docker build -t express-master .
        sudo docker run --name express-master -d -p 80:80 express-master    
            
            
            
            
            
            
        
